http:
  port: 9875

apiEndpoints:
  nts:
    host: localhost
    paths: "/nts/*"
  fts:
    host: localhost
    paths: "/fts/*"

serviceEndpoints:
  nts:
    urls:
      - "http://35.88.165.47:3000"
  fts:
    urls:
      - "http://35.88.165.47:8000"

policies:
  - proxy
pipelines:
  fts:
    apiEndpoints:
      - fts
    policies:
      - proxy:
          - action:
              serviceEndpoint: fts
              changeOrigin: true
  nts:
    apiEndpoints:
      - nts
    policies:
      - proxy:
          - action:
              serviceEndpoint: nts
              changeOrigin: true

  # default:
  #   apiEndpoints:
  #     - api
  #   policies:
  #   - proxy:
  #       - action:
  #           condition: "request.url.path.startsWith('/parametros/gerencia')"
  #           serviceEndpoint: fastApi
  #           changeOrigin: true
  #       - action:
  #           serviceEndpoint: nestApi
  #           changeOrigin: true



    # url: 'http://35.88.165.47:3000'
    # url: 'http://192.168.70.156:3000'
